### ISSUE TITLE
The color selection box area is broken. Even the demo page breaks.

### ISSUE THREAD

**Issue by kimho** [flaming-cl/editorjs-text-color-plugin#22] opened 2023-06-11 07:38 UTC
As shown in the image below, if you access the [demo page](https://flaming-cl.github.io/editorPlugin/) and check it, you can see that the selected area is broken. please fix the bug.

<img width="315" alt="스크린샷 2023-06-11 오후 4 32 38" src="https://github.com/flaming-cl/editorjs-text-color-plugin/assets/462117/86210442-40d4-4a74-8a0a-e342fbea1696">

**Comment by flaming-cl** [comment] 2023-06-11 11:00
Same issue as https://github.com/flaming-cl/editorjs-text-color-plugin/issues/21
Caused by new Chrome release

**Comment by flaming-cl** [comment] 2023-06-14 23:28
It's fixed in v2.0.3 now. Thanks for bringing up this issue!

**Closed** 2023-06-15 18:02 UTC
Labels: Chrome 114
